#!/usr/bin/env sh

# check if one or multiple monitors are connected. 0 = dual, 1 = single
MODE=$(yabai -m query --displays | jq '. |length % 2')
RESOLUTION=$(yabai -m query --displays | jq '.[0].frame.w')

# source config accordingly
if [[ $MODE == 0 ]]; then
	echo "use dual-monitor setup"
	#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
	#sudo yabai --load-sa

	# default layout (can be bsp, stack or float)
	yabai -m config layout bsp
	yabai -m config auto_balance on
	#yabai -m config split_ratio 0.52

	# Set all padding (default: 0)
	yabai -m config top_padding 9
	yabai -m config bottom_padding 9
	yabai -m config left_padding 9
	yabai -m config right_padding 9
	yabai -m config window_gap 9

	# new window spawns to the right if vertical split, or bottom if horizontal split
	#yabai -m config window_placement first_child

	# center mouse on window with focus
	yabai -m config mouse_follows_focus on
	# focus window under cursor
	yabai -m config focus_follows_mouse autofocus
	# modifier for clicking and dragging with mouse
	yabai -m config mouse_modifier alt
	# set modifier + left-click drag to move window
	yabai -m config mouse_action1 move
	# set modifier + right-click drag to resize window
	yabai -m config mouse_action2 resize
	# when window is dropped in center of another window, swap them (on edges it will split it)
	yabai -m config mouse_drop_action stack

	# disable specific apps
	yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
	yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
	yabai -m rule --add label="App Store" app="^App Store$" manage=off
	yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
	yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
	yabai -m rule --add label="Finder" app="^Finder$" manage=off
	yabai -m rule --add label="Raycast" app="^Raycast" manage=off
	yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off
	yabai -m rule --add label="Preview" app="^Preview$" manage=off

	# configure spaces
	yabai -m space 5 --label "social"
	yabai -m config --space 5 layout stack
	yabai -m rule --add app="Telegram" space=^social
	yabai -m rule --add app="WhatsApp" space=^social
	yabai -m rule --add app="Signal" space=^social
	yabai -m rule --add app="Spotify" space=^social
	yabai -m rule --add app="Messages" space=^social

	yabai -m space 1 --label "mail"
	yabai -m config --space 1 layout bsp
	yabai -m rule --add app="Mail" space=^mail

	yabai -m space 2 --label "business"
	yabai -m config --space 2 layout bsp
	yabai -m rule --add app="Outlook" space=^business

	yabai -m space 3 --label "kindi"
	yabai -m config --space 3 layout bsp

	yabai -m space 4 --label "code"
	yabai -m config --space 4 layout bsp
	yabai -m rule --add app="Alacritty" space=^code
	yabai -m rule --add app="Code" space=^code

	echo "yabai configuration loaded.."

elif [[ $RESOLUTION == "5120.0000" ]]; then
	#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
	#sudo yabai --load-sa

	# default layout (can be bsp, stack or float)
	yabai -m config layout bsp
	#yabai -m config auto_balance off
	#yabai -m config split_ratio 0.52

	# Set all padding (default: 0)
	yabai -m config top_padding 9
	yabai -m config bottom_padding 9
	yabai -m config left_padding 9
	yabai -m config right_padding 9
	yabai -m config window_gap 9

	# new window spawns to the right if vertical split, or bottom if horizontal split
	yabai -m config window_placement second_child

	# center mouse on window with focus
	yabai -m config mouse_follows_focus off
	# focus window under cursor
	yabai -m config focus_follows_mouse autofocus
	# modifier for clicking and dragging with mouse
	yabai -m config mouse_modifier alt
	# set modifier + left-click drag to move window
	yabai -m config mouse_action1 move
	# set modifier + right-click drag to resize window
	yabai -m config mouse_action2 resize
	# when window is dropped in center of another window, swap them (on edges it will split it)
	yabai -m config mouse_drop_action stack

	# disable specific apps
	yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
	yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
	yabai -m rule --add label="App Store" app="^App Store$" manage=off
	yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
	yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
	yabai -m rule --add label="Finder" app="^Finder$" manage=off
	yabai -m rule --add label="Raycast" app="^Raycast" manage=off
	yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off
	yabai -m rule --add label="Preview" app="^Preview$" manage=off

	# configure spaces
	yabai -m space 1 --label "social"
	yabai -m config --space 1 layout bsp
	yabai -m rule --add app="Mail" space=^social
	yabai -m rule --add app="Telegram" space=^social
	yabai -m rule --add app="Whatsapp" space=^social
	yabai -m rule --add app="Signal" space=^social
	yabai -m rule --add app="Spotify" space=^social
	yabai -m rule --add app="Messages" space=^social

	yabai -m space 2 --label "business"
	yabai -m config --space 2 layout bsp
	yabai -m rule --add app="Outlook" space=^business

	yabai -m space 3 --label "kindi"
	yabai -m config --space 3 layout bsp

	yabai -m space 4 --label "code"
	yabai -m config --space 4 layout bsp
	yabai -m rule --add app="Alacritty" space=^code
	yabai -m rule --add app="Code" space=^code

	# configure events
	#yabai -m signal --add event=display_changed action="source ~/.config/yabai/scripts/set_index.sh"
	echo "use 49" home setup""

else
	#yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"
	#sudo yabai --load-sa

	# default layout (can be bsp, stack or float)
	yabai -m config layout stack
	#yabai -m config auto_balance off
	#yabai -m config split_ratio 0.52

	# Set all padding (default: 0)
	yabai -m config top_padding 9
	yabai -m config bottom_padding 9
	yabai -m config left_padding 9
	yabai -m config right_padding 9
	yabai -m config window_gap 9

	# new window spawns to the right if vertical split, or bottom if horizontal split
	yabai -m config window_placement second_child

	# center mouse on window with focus
	yabai -m config mouse_follows_focus off
	# focus window under cursor
	yabai -m config focus_follows_mouse autofocus
	# modifier for clicking and dragging with mouse
	yabai -m config mouse_modifier alt
	# set modifier + left-click drag to move window
	yabai -m config mouse_action1 move
	# set modifier + right-click drag to resize window
	yabai -m config mouse_action2 resize
	# when window is dropped in center of another window, swap them (on edges it will split it)
	yabai -m config mouse_drop_action stack

	# disable specific apps
	yabai -m rule --add label="Activity Monitor" app="^Activity Monitor$" manage=off
	yabai -m rule --add label="System Settings" app="^System Settings$" manage=off
	yabai -m rule --add label="App Store" app="^App Store$" manage=off
	yabai -m rule --add label="Calculator" app="^Calculator$" manage=off
	yabai -m rule --add label="Finder" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
	yabai -m rule --add label="Finder" app="^Finder$" manage=off
	yabai -m rule --add label="Raycast" app="^Raycast" manage=off
	yabai -m rule --add label="Karabiner-Elements" app="^Karabiner-Elements$" manage=off
	yabai -m rule --add label="Preview" app="^Preview$" manage=off

	# configure spaces
	yabai -m space 1 --label "social"
	yabai -m config --space 1 layout stack
	yabai -m rule --add app="Mail" space=^social
	yabai -m rule --add app="Telegram" space=^social
	yabai -m rule --add app="Whatsapp" space=^social
	yabai -m rule --add app="Signal" space=^social
	yabai -m rule --add app="Spotify" space=^social
	yabai -m rule --add app="Messages" space=^social

	yabai -m space 2 --label "business"
	yabai -m config --space 2 layout stack
	yabai -m rule --add app="Outlook" space=^business

	yabai -m space 3 --label "kindi"
	yabai -m config --space 3 layout stack

	yabai -m space 4 --label "code"
	yabai -m config --space 4 layout stack
	yabai -m rule --add app="Alacritty" space=^code
	yabai -m rule --add app="Code" space=^code

	# configure events
	#yabai -m signal --add event=display_changed action="source ~/.config/yabai/scripts/set_index.sh"
	echo "use macbook monitor setup"
fi

yabai -m signal --add event=display_added action="source ~/.config/yabai/yabairc"
yabai -m signal --add event=display_removed action="source ~/.config/yabai/yabairc"
