import = [
    "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 1, y = 1 }
dynamic_padding = false
decorations = "Buttonless"
#opacity = 0.7
#blur = true
option_as_alt = "Both"
dynamic_title = false

[selection]
save_to_clipboard = true

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Light" }
size = 13

[keyboard]
bindings = [
  { key = "Right", mods = "Alt", chars = "\u001BF" },
  { key = "Left",  mods = "Alt", chars = "\u001BB" },
]

#[misc]
[shell]
program = "/bin/zsh"
args = [ "-l", "-c", "tmux attach || tmux new " ]
